apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: zookeeper-2-claim1
  name: zookeeper-2-claim1
spec:
  storageClassName: kafka-cert-b
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
