// © Copyright IBM Corporation 2020. All rights reserved.
// SPDX-License-Identifier: Apache2.0
// 
package payment

var (

	SETTLEMENT_METHOD_DIGITAL_ASSET = "DA"
	SETTLEMENT_METHOD_DIGITAL_OBLIGATION = "DO"
	SETTLEMENT_METHOD_XLM = "XLM"
	PAYMENT_STATUS_INITIAL = "INITIAL"
	PAYMENT_STATUS_VALIDATION_FAIL = "VALIDATION_FAIL"
	PAYMENT_STATUS_VALIDATION_SUCCESS = "VALIDATION_SUCCESS"
	PAYMENT_STATUS_FEDERATION_SUCCESS = "FEDERATION_SUCCESS"
	PAYMENT_STATUS_FEDERATION_FAIL = "FEDERATION_FAIL"
	PAYMENT_STATUS_COMPLIANCE_SUCCESS = "COMPLIANCE_SUCCESS"
	PAYMENT_STATUS_COMPLIANCE_FAIL = "COMPLIANCE_FAIL"
	PAYMENT_STATUS_SUBMIT_FAIL ="SUBMIT_FAIL"
	PAYMENT_STATUS_CLEARED = "CLEARED"
	PAYMENT_STATUS_SETTLED = "SETTLED"
)
