apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: kafka-2-claim0
  name: kafka-2-claim0
spec:
  storageClassName: kafka-cert-b
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
