apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    app: kafka-2-claim1
  name: kafka-2-claim1
spec:
  storageClassName: kafka-cert-b
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
status: {}
