apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: participant_id_variable
spec:
  hosts:
  - "participant_id_variable.host_variable.io"
  gateways:
  - worldwire-gateway
  http:
  - match:
    - uri:
        prefix: /gateway/
    route:
    - destination:
        port:
          number: 9000
        host: participant_id_variable-gateway.default.svc.cluster.local
    rewrite:
      uri: /
---