// © Copyright IBM Corporation 2020. All rights reserved.
// SPDX-License-Identifier: Apache2.0
// 
// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Upload Upload
//
// Upload aws secret, k8s secret and config map to database for version control
// swagger:model Upload
type Upload struct {

	// Encoded secret store in AWS secret manager
	AwsSecret string `json:"awsSecret,omitempty"`

	// Encoded K8s ConfigMap
	ConfigMap string `json:"configMap,omitempty"`

	// Encoded K8s secret
	K8sSecret string `json:"k8sSecret,omitempty"`

	// version
	// Required: true
	Version *string `json:"version"`
}

// Validate validates this upload
func (m *Upload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVersion(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Upload) validateVersion(formats strfmt.Registry) error {

	if err := validate.Required("version", "body", m.Version); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Upload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Upload) UnmarshalBinary(b []byte) error {
	var res Upload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
