[general]
access-control-allow-origin="*"

[logging]
level="info"
maxsize=100
maxbackups=30
maxage=10
use-localtime=false
use-compression=true

[zookeeper]
servers=[ "10.0.101.74:2181", "10.0.102.193:2181", "10.0.103.128:2181" ]
timeout=6
root-path="/burrow"

[cluster.ww-qa-msk]
class-name="kafka"
servers=[ "b-1.ww-qa-msk.fjuh42.c2.kafka.us-west-2.amazonaws.com:9094", "b-3.ww-qa-msk.fjuh42.c2.kafka.us-west-2.amazonaws.com:9094", "b-2.ww-qa-msk.fjuh42.c2.kafka.us-west-2.amazonaws.com:9094" ]
client-profile="test"
topic-refresh=120
offset-refresh=30

[consumer.ww-qa-msk]
class-name="kafka"
cluster="ww-qa-msk"
servers=[ "b-1.ww-qa-msk.fjuh42.c2.kafka.us-west-2.amazonaws.com:9094", "b-3.ww-qa-msk.fjuh42.c2.kafka.us-west-2.amazonaws.com:9094", "b-2.ww-qa-msk.fjuh42.c2.kafka.us-west-2.amazonaws.com:9094" ]
client-profile="test"
group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
group-whitelist=""

[consumer.ww-qa-msk_zk]
class-name="kafka_zk"
cluster="ww-qa-msk"
servers=[ "10.0.101.74:2181", "10.0.102.193:2181", "10.0.103.128:2181" ]
zookeeper-path="/kafka-cluster"
zookeeper-timeout=30
group-blacklist="^(console-consumer-|python-kafka-consumer-|quick-).*$"
group-whitelist=""

[httpserver.default]
address=":8000"

[client-profile.test]
client-id="burrow-test"
kafka-version="1.1.0"
tls="tlsonly"

[tls.tlsonly]
certfile="/var/private/ssl/kafka_cert.crt"
keyfile="/var/private/ssl/decrypted_key.key"
cafile="/var/private/ssl/ca_cert.crt"
noverify=true

#[storage.default]
#class-name="inmemory"
#workers=20
#intervals=15
#expire-group=604800
#min-distance=1
#
#[notifier.default]
#class-name="http"
#url-open="http://someservice.example.com:1467/v1/event"
#interval=60
#timeout=5
#keepalive=30
#extras={ api_key="REDACTED", app="burrow", tier="STG", fabric="mydc" }
#template-open="conf/default-http-post.tmpl"
#template-close="conf/default-http-delete.tmpl"
#method-close="DELETE"
#send-close=true
#threshold=1