[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.da1]
    NODE_ADDRESS = "GDBIAFVTAUBPP3MNNXPED3BDAE6E7BBLS537ZS2NEE27P6H3SRJMN7CH"
    NODE_SEED = "(seed value)"

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GDPCVTQQH423VSBLM6VAJOCEKU2PT5MCZNDL7PNMMJTCCJA3O56ORGXD"
    NODE_SEED = "(seed value)"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBSWQMTC4MCYLN2XSCXM7ZQL3XPPD2K52YD7GED33T6DHAPHKDFUMI7P"
  NODE_SEED = "(seed value)"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GDNTT3VZN7KASCNETM7SC4BB5KHG6MUPZVKFV6FSVMERHAWLQTX7WM5L"
  NODE_SEED = "(seed value)"

[WHITE_LIST]
  PARTICIPANT_DOMAINS = "sg.one.payments.gftn.io"
