
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.da1]
    NODE_ADDRESS = "GBTJVFAAZCRJG4TXAMADCBDQ6RJGYJJ34XAJLONUSQA5YCPB2356IUBJ"
    NODE_SEED = "(seed value)"

  [DISTRIBUTION_ACCOUNTS.da2]
    NODE_ADDRESS = "GDSVFKYAC6KKREKYYZA7RMGKDC6JXNA35IDT5PKGB3UHWYFIR7U4LXMG"
    NODE_SEED = "(seed value)"

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GA7D2ZZHDRELM7G3DVXSNYGLXPTMFVHTJOQZ3SKSCBDR7DHPPAQS2OW6"
    NODE_SEED = "(seed value)"

  [DISTRIBUTION_ACCOUNTS.tom1]
    NODE_ADDRESS = "GCBAHUHTU4TJ5KXOTONCW4MJQEOMAOHPCINURDWQO6AUBFBNZJHVYXP7"
    NODE_SEED = "(seed value)"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBSWQMTC4MCYLN2XSCXM7ZQL3XPPD2K52YD7GED33T6DHAPHKDFUMI7P"
  NODE_SEED = "(seed value)"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GA3UQQ7HQC4JJZCQO5IWZDZRJV2UHY5SS6MOU36H2QSIBNATZAXJZSMK"
  NODE_SEED = "(seed value)"

[WHITE_LIST]
  PARTICIPANT_DOMAINS = "testdomain.com;"
