
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.OperatingAccX]
    NODE_ADDRESS = "GAUQGUNPII6QU3WTIOBZHJV55GO5FEGKPXC37SPQB2XVHVAZEPK3GTRM"
    NODE_SEED = "(seed value)"

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GAM5QC6M26ZWMOZZL6SANRZ6RGYAWRQJDEWBALHYZWWGIUCVAGAJD4ZF"
    NODE_SEED = "(seed value)"

  [DISTRIBUTION_ACCOUNTS.sagu]
    NODE_ADDRESS = "GCPB2TJK4CHAXESIGZIHVJMBQ2SK4I6UUKHPU7BWL7MCJF3ESC7SZ6TG"
    NODE_SEED = "(seed value)"

  [DISTRIBUTION_ACCOUNTS.seema]
    NODE_ADDRESS = "GBJT2KDHBTNRNZVCFPWLDIMUSJTRU5SZIDXJCGIKLGX5F2DYTXJE2BS2"
    NODE_SEED = "(seed value)"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GCZN5K3MKKTYHZ6RLOJHOH3W7WUIKSYCOZXFJYF6DWGWEPEGAS4MTPIV"
  NODE_SEED = "(seed value)"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GC3ZBVI7VKIGNNHZQ54ZJSORIZQHVQUTJ5CY2I4BRM4MLO6UHBSZXJ74"
  NODE_SEED = "(seed value)"