[DISTRIBUTION_ACCOUNTS]

 [DISTRIBUTION_ACCOUNTS.default]
   NODE_ADDRESS = "GCUIXHQV3VOVGBKJLOMI5NBHDBTNQ6A5IQXCSENVZ3OU63FSTMFRZ2H2"
   NODE_SEED = "(seed value)"
 [DISTRIBUTION_ACCOUNTS.test1]
   NODE_ADDRESS = "GASCCP5TACQKI3SVMADRDKCLUNO4UOFGXNHYFNO7ONLIA3VZGYC3LVLJ"
   NODE_SEED = "(seed value)"

[IBM_TOKEN_ACCOUNT]
 NODE_ADDRESS = "GBSWQMTC4MCYLN2XSCXM7ZQL3XPPD2K52YD7GED33T6DHAPHKDFUMI7P"
 NODE_SEED = "(seed value)"


[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GDHN4EOLOYSOZXGZK2LALH4FXFI33OAOP5XHIRNF65EIJPY7KAWOULH6"
  NODE_PASS_CODE = "554e6f884f11b65b51e327598631f52ceac18d2591e0d52f66b3fa6b57c5fe7de8f640c47e81267fa3e13fa076c1f83526fc6fbf4e763e592d368292df909990"
  NODE_SEED = "(seed value)"


[WHITE_LIST]
 PARTICIPANT_DOMAINS = "au.one.payments.gftn.io"