
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.doesntexist]
    NODE_ADDRESS = "FakeOperatingAccount"
    NODE_SEED = "(seed value)"


[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBSWQMTC4MCYLN2XSCXM7ZQL3XPPD2K52YD7GED33T6DHAPHKDFUMI7P"
  NODE_PASS_CODE = ""
  NODE_SEED = "(seed value)"
