[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.sudu]
    NODE_ADDRESS = "GCC5EELCA2NGCODAWG7BIYZLAADEVICGTNOWNNSB4GF7NIRCUDLE3VKH"
    NODE_PASS_CODE = "4dc277e0851287f49a0b264acc5fc1176891ed2fb5d35ad039bae4631d713a79"
    NODE_SEED = "(seed value)"

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GCPAWR3SDTGDJP7DBUAQBPSU6BV7IABEILMO4ZBPULNVCMITO4FIACQG"
    NODE_PASS_CODE = "800db7d542df151cf4b8f809f14ed32b4b6eb99f0b4e2501f633ebf807a4f0e7"
    NODE_SEED = "(seed value)"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GD3ISWRGX3YMXS6NT4W7SLLVAOCEQZRCIEGH6XLQCAE3MAZ2GRGMWHYZ"
  NODE_PASS_CODE = ""
  NODE_SEED = "(seed value)"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GBYTUJOTBAERUJMM5DTDDM4XLCQ3SC27C2AWFVSQDSF2XNMVOI6NMVW4"
  NODE_PASS_CODE = "265a3f3532aef24049a2524a9eaa807e0a2e255fef8af62a4be97e13f8bac7c7"
  NODE_SEED = "(seed value)"

[WHITE_LIST]
    PARTICIPANT_DOMAINS = "usd.us.stronghold.co;ie.one.payments.worldwire.io;"

