swagger: "2.0"
info:
  title: GFTN API Service Internal; API
  description: Private API for inter-component communication within the participant's GFTN instance.
  version: 1.0.0
host: api.gftn.io
basePath: /v1/internal
schemes:
  - https
paths:

 /accounts/{account_name}:
    get:
      tags:
        - Operating Account
        - Issuing Account
      summary: retrieve a operating or issuing account
      description: |
        retrieve the operating or issuing account for a participant
      produces:
        - application/json
      parameters:
        - in: path
          name: account_name
          type: string
          required: true
          description: a name to identify this account, use "issuing" as account_name for issuing account
      responses:
        200:
          description: Account found
          schema:
            $ref: '../../gftn-models/models/operatingAccount.yaml'
        400:
          description: missing or invalid parameters in the request
        404:
          description: The operating account could not be found
    post:
      tags:
        - Operating or issing Account Creation
      summary: Called when an originator wants to create a new  account
      description: |
        During client onboarding, each client will require atleast one  operating account named "default". and "issuing" account
      produces:
        - application/json
      parameters:
        - in: path
          name: account_name
          type: string
          required: true
          description: a name to identify this account
      responses:
        208:
          description: Operating or issuing Account created or already exists
          schema:
            $ref: '../../gftn-models/models/operatingAccount.yaml'
        400:
          description: missing or invalid parameters in the request
        404:
          description: The operating or issuing account could not be created


    post:
      tags:
        - Issuing Account Creation
      summary: Called when an originator wants to create a new issuing account
      description: |
        During client onboarding, each client will require one issuing account. this API creates the issuing account
      produces:
        - application/json
      responses:
        208:
          description: Issuing Account created or already exists
          schema:
            $ref: '../../gftn-models/models/operatingAccount.yaml'
        404:
          description: The issuing account could not be created
