// © Copyright IBM Corporation 2020. All rights reserved.
// SPDX-License-Identifier: Apache2.0
// 
// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// AccountFoundResponse accountFoundResponse
//
// Account Found Response
// swagger:model AccountFoundResponse
type AccountFoundResponse struct {

	// Other info returned about the participant or the final receiver
	OtherInfo string `json:"other_info,omitempty"`

	// The stellar address to interact with in the context of this transaction
	// Required: true
	StellarNetworkAddress *string `json:"stellar_network_address"`
}

// Validate validates this account found response
func (m *AccountFoundResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStellarNetworkAddress(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AccountFoundResponse) validateStellarNetworkAddress(formats strfmt.Registry) error {

	if err := validate.Required("stellar_network_address", "body", m.StellarNetworkAddress); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AccountFoundResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AccountFoundResponse) UnmarshalBinary(b []byte) error {
	var res AccountFoundResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
