// © Copyright IBM Corporation 2020. All rights reserved.
// SPDX-License-Identifier: Apache2.0
// 
// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DestInfo destInfo
//
// Dest Info
// swagger:model DestInfo
type DestInfo struct {

	// AML/KYC/Sanctions info of the recipient
	// Required: true
	AmlKycInfo *string `json:"aml_kyc_info"`

	// The unique identifier for the compliance check done prior to this payment
	// Required: true
	ComplianceIdentification *string `json:"compliance_identification"`
}

// Validate validates this dest info
func (m *DestInfo) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmlKycInfo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateComplianceIdentification(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DestInfo) validateAmlKycInfo(formats strfmt.Registry) error {

	if err := validate.Required("aml_kyc_info", "body", m.AmlKycInfo); err != nil {
		return err
	}

	return nil
}

func (m *DestInfo) validateComplianceIdentification(formats strfmt.Registry) error {

	if err := validate.Required("compliance_identification", "body", m.ComplianceIdentification); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *DestInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DestInfo) UnmarshalBinary(b []byte) error {
	var res DestInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
