// © Copyright IBM Corporation 2020. All rights reserved.
// SPDX-License-Identifier: Apache2.0
// 
// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Draft draft
//
// draft
// swagger:model Draft
type Draft struct {

	// The name of the account with which the transactions needs to be signed
	// Required: true
	AccountName *string `json:"account_name"`

	// This will be signed reference envelope to verify against partcipant's signature for authenticity.
	// Required: true
	// Format: byte
	IDSigned *strfmt.Base64 `json:"id_signed"`

	// This will be unsigned reference envelope to verify against partcipant's signature for authenticity.
	// Required: true
	// Format: byte
	IDUnsigned *strfmt.Base64 `json:"id_unsigned"`

	// Identifier for transaction.
	TransactionID string `json:"transaction_id,omitempty"`

	// The unsigned transaction envelope to be signed by the participant.
	// Required: true
	// Format: byte
	TransactionUnsigned *strfmt.Base64 `json:"transaction_unsigned"`
}

// Validate validates this draft
func (m *Draft) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccountName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIDSigned(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIDUnsigned(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransactionUnsigned(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Draft) validateAccountName(formats strfmt.Registry) error {

	if err := validate.Required("account_name", "body", m.AccountName); err != nil {
		return err
	}

	return nil
}

func (m *Draft) validateIDSigned(formats strfmt.Registry) error {

	if err := validate.Required("id_signed", "body", m.IDSigned); err != nil {
		return err
	}

	// Format "byte" (base64 string) is already validated when unmarshalled

	return nil
}

func (m *Draft) validateIDUnsigned(formats strfmt.Registry) error {

	if err := validate.Required("id_unsigned", "body", m.IDUnsigned); err != nil {
		return err
	}

	// Format "byte" (base64 string) is already validated when unmarshalled

	return nil
}

func (m *Draft) validateTransactionUnsigned(formats strfmt.Registry) error {

	if err := validate.Required("transaction_unsigned", "body", m.TransactionUnsigned); err != nil {
		return err
	}

	// Format "byte" (base64 string) is already validated when unmarshalled

	return nil
}

// MarshalBinary interface implementation
func (m *Draft) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Draft) UnmarshalBinary(b []byte) error {
	var res Draft
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
