// © Copyright IBM Corporation 2020. All rights reserved.
// SPDX-License-Identifier: Apache2.0
// 
// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// FundingInstruction fundingInstruction
//
// Funding Instruction
// swagger:model FundingInstruction
type FundingInstruction struct {

	// details funding
	DetailsFunding *Funding `json:"details_funding,omitempty"`

	// Unsigned transaction xdr related to the funding. This will need to be signed in the next step.
	//
	InstructionUnsigned string `json:"instruction_unsigned,omitempty"`
}

// Validate validates this funding instruction
func (m *FundingInstruction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDetailsFunding(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *FundingInstruction) validateDetailsFunding(formats strfmt.Registry) error {

	if swag.IsZero(m.DetailsFunding) { // not required
		return nil
	}

	if m.DetailsFunding != nil {
		if err := m.DetailsFunding.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("details_funding")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *FundingInstruction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *FundingInstruction) UnmarshalBinary(b []byte) error {
	var res FundingInstruction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
