// © Copyright IBM Corporation 2020. All rights reserved.
// SPDX-License-Identifier: Apache2.0
// 
// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InternalAdminDraft internalAdminDraft
//
// draft
// swagger:model InternalAdminDraft
type InternalAdminDraft struct {

	// The unsigned transaction envelope to be signed by IBM account.
	// Required: true
	// Format: byte
	TransactionUnsigned *strfmt.Base64 `json:"transaction_unsigned"`
}

// Validate validates this internal admin draft
func (m *InternalAdminDraft) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTransactionUnsigned(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InternalAdminDraft) validateTransactionUnsigned(formats strfmt.Registry) error {

	if err := validate.Required("transaction_unsigned", "body", m.TransactionUnsigned); err != nil {
		return err
	}

	// Format "byte" (base64 string) is already validated when unmarshalled

	return nil
}

// MarshalBinary interface implementation
func (m *InternalAdminDraft) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InternalAdminDraft) UnmarshalBinary(b []byte) error {
	var res InternalAdminDraft
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
