// © Copyright IBM Corporation 2020. All rights reserved.
// SPDX-License-Identifier: Apache2.0
// 
// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PayoutLocationUpdateRequest payoutLocationUpdateRequest
//
// List of updated payout location attributes. Based on https://schema.org/LocalBusiness
// swagger:model PayoutLocationUpdateRequest
type PayoutLocationUpdateRequest struct {

	// The identifier of the payout location
	// Required: true
	ID *string `json:"id"`

	// updated payload
	// Required: true
	UpdatedPayload *PayoutLocation `json:"updated_payload"`
}

// Validate validates this payout location update request
func (m *PayoutLocationUpdateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdatedPayload(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PayoutLocationUpdateRequest) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *PayoutLocationUpdateRequest) validateUpdatedPayload(formats strfmt.Registry) error {

	if err := validate.Required("updated_payload", "body", m.UpdatedPayload); err != nil {
		return err
	}

	if m.UpdatedPayload != nil {
		if err := m.UpdatedPayload.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updated_payload")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PayoutLocationUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PayoutLocationUpdateRequest) UnmarshalBinary(b []byte) error {
	var res PayoutLocationUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
