// © Copyright IBM Corporation 2020. All rights reserved.
// SPDX-License-Identifier: Apache2.0
// 
// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SignedTransaction signedTransaction
//
// signedTransaction
// swagger:model SignedTransaction
type SignedTransaction struct {

	// reference transaction id, same as sent in the request
	TransactionID string `json:"transaction_id,omitempty"`

	// signed transaction envelope which is signed by the participant
	// Required: true
	// Format: byte
	TransactionSigned *strfmt.Base64 `json:"transaction_signed"`
}

// Validate validates this signed transaction
func (m *SignedTransaction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTransactionSigned(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SignedTransaction) validateTransactionSigned(formats strfmt.Registry) error {

	if err := validate.Required("transaction_signed", "body", m.TransactionSigned); err != nil {
		return err
	}

	// Format "byte" (base64 string) is already validated when unmarshalled

	return nil
}

// MarshalBinary interface implementation
func (m *SignedTransaction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SignedTransaction) UnmarshalBinary(b []byte) error {
	var res SignedTransaction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
