// © Copyright IBM Corporation 2020. All rights reserved.
// SPDX-License-Identifier: Apache2.0
// 
// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// StrongholdPaymentInstructions stronghold payment instructions
// swagger:model StrongholdPaymentInstructions
type StrongholdPaymentInstructions struct {

	// amount
	Amount string `json:"amount,omitempty"`

	// a reference hash to refer transaction in anchor's system of record
	PayToReference string `json:"pay_to_reference,omitempty"`

	// address to return back to
	PayToVenueSpecific string `json:"pay_to_venue_specific,omitempty"`
}

// Validate validates this stronghold payment instructions
func (m *StrongholdPaymentInstructions) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *StrongholdPaymentInstructions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *StrongholdPaymentInstructions) UnmarshalBinary(b []byte) error {
	var res StrongholdPaymentInstructions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
