[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GADCW4YOX3B4QH6R4KLUZHUZJ4U243XYDPL4UV2SZGBIC2DI2IKEQUII"
    NODE_SEED = "(seed value)"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBSWQMTC4MCYLN2XSCXM7ZQL3XPPD2K52YD7GED33T6DHAPHKDFUMI7P"
  NODE_SEED = "(seed value)"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GAYVH6X3DGH7D7ZQY2PUUZV2RT2EUEULSEWOFDSTE7IC3S3QLT6H262F"
  NODE_SEED = "(seed value)"
