
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GC42RQF6NC7ZQ4JM4EBZHYBDZRKBCVGKQTD5XY2WRKJSRF2ZJUKERV7T"
    NODE_PASS_CODE = ""
    NODE_SEED = "(seed value)"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GD2RP3XK2AU2NMMG5AIXBBIZVPGKBUZVKIUTT5NCXG6LHD6FFN7UJGW2"
  NODE_PASS_CODE = ""
  NODE_SEED = "(seed value)"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GA3Z5DS6GAPBI6EGRFRCEJKAFBZHESW62U5ME3OJYVD5VEREY5ENTGIK"
  NODE_PASS_CODE = ""
  NODE_SEED = "(seed value)"

[WHITE_LIST]
  PARTICIPANT_DOMAINS = "ie.one.payments.worldwire.io;usd.us.stronghold.co;"
