[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GDTKBZ2AZROVIKRH37A2VNHHC3UADOMBC3IJFF5PJBGB7OJEFTTVIYXL"
    NODE_SEED = "(seed value)"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBC7RNHM4B4IMO56A2ZJQIN2ZT2FA2VUMEK5UIWZMROLVLGNI4O6Z2WA"
  NODE_SEED = "(seed value)"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GA3R6DKDA2B554KHCQIEJE5FLTXRMRIAD3O236JBUEXLA3764C4D4NKV"
  NODE_SEED = "(seed value)"

[WHITE_LIST]
  PARTICIPANT_DOMAINS = "usd.us.stronghold.co;ie.one.payments.worldwire.io"
