
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GCBUP7FPYKPLFHVPFZC76SZBV4IY6K2WNSWBG7IKGP5Q4SXKUMG6URB3"
    NODE_SEED = "(seed value)"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GBSWQMTC4MCYLN2XSCXM7ZQL3XPPD2K52YD7GED33T6DHAPHKDFUMI7P"
  NODE_SEED = "(seed value)"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GD6TEBVZ3ILXMOFFYMN2RUKIYBGBCUOO3M6C4VAAI5Z5WUAXZ5OETTUL"
  NODE_SEED = "(seed value)"

