apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-3zk-3b-ssl.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    app: kafka-2
  name: kafka-2
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  - name: "kafka-2-19092"
    port: 19092
    targetPort: 19092
  selector:
    app: kafka-2
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-2-headless
  name: kafka-2-headless
spec:
  clusterIP: None
  ports:
  - port: 9092
    protocol: TCP
    targetPort: 9092
  selector:
    app: kafka-2
  sessionAffinity: None
  type: ClusterIP