apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-3zk-3b-ssl.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    app: kafka-1
  name: kafka-1
spec:
  ports:
  - name: "9091"
    port: 9091
    targetPort: 9091
  - name: "kafka-1-19092"
    port: 19092
    targetPort: 19092
  selector:
    app: kafka-1
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-1-headless
  name: kafka-1-headless
spec:
  clusterIP: None
  ports:
  - port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: kafka-1
  sessionAffinity: None
  type: ClusterIP