apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-3zk-3b-ssl.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    app: kafka-3
  name: kafka-3
spec:
  ports:
  - name: "9093"
    port: 9093
    targetPort: 9093
  - name: "kafka-3-19092"
    port: 19092
    targetPort: 19092
  selector:
    app: kafka-3
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-3-headless
  name: kafka-3-headless
spec:
  clusterIP: None
  ports:
  - port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    app: kafka-3
  sessionAffinity: None
  type: ClusterIP