// © Copyright IBM Corporation 2020. All rights reserved.
// SPDX-License-Identifier: Apache2.0
// 
package persistence

type FItoFICCTMemoData struct {
	ID string `json:"_id,omitempty" bson:"_id,omitempty"`

	// fitoficct non pii data
	// Required: true
	FitoficctNonPiiData *FItoFICCTNonPiiData `json:"fitoficctnonpiidata"  bson:"fitoficctnonpiidata"`

	// the hash value of the FItoFICCTPiiData
	// Required: true
	FitoficctPiiHash *string `json:"fitoficct_pii_hash" bson:"fitoficct_pii_hash"`

	// this is the unique id for this transaction generated by the distributed ledger (but not in txn memo hash)
	TransactionIdentifier string `json:"transaction_identifier,omitempty"  bson:"transaction_identifier,omitempty"`
	// the participant domain of the OFI (payment sender)
	// Required: true
	OfiDomain *string `json:"ofi_domain" bson:"ofi_domain"`

	// the timestamp for this transaction
  	// Required: true
	TimeStamp *int64 `json:"time_stamp" bson:"time_stamp"`

	// transaction status
	// Required: true
	TransactionStatus *string `json:"transaction_status" bson:"transaction_status"`
	//TransactionStatus []*FItoFITransactionStatus `json:"transaction_status" bson:"transaction_status"`
}
