[DISTRIBUTION_ACCOUNTS]



[IBM_TOKEN_ACCOUNT]
 NODE_ADDRESS = "GB6KMNQODYL5QGS3NFXAQYNFDK6RSDKWNV4BTPP6AQZTKURUFBB2KMY4"
 NODE_PASS_CODE = ""
 NODE_SEED = "(seed value)"
 PrivateKeyLabel = ""
 PublicKeyLabel = ""

[ISSUING_ACCOUNT]


[WHITE_LIST]
 PARTICIPANT_DOMAINS = ""
