
Feature: World Wire goodCase/5_exchange/1_exchange_asset_between_participants
  In order to helping a customer send money
  As a developer
  I want to exchange asset between participants in Worldwire

  Scenario Outline: exchange assets between participants
    Given id: <participant_id> check participant: <rfi_participant_id>, was in Workd Wire, apiURL: <participant_api_url>
    And id: <participant_id> check participant: <rfi_participant_id> was in the whitelist - whitelistURL: <global_whitelist_url>
    And id: <rfi_participant_id> check participant: <participant_id> was in the whitelist - whitelistURL: <global_whitelist_url>
    And id: <participant_id> request a exchange_requset with time_expire: <ofi_time_expire> limit_max: <limit_max> limit_min: <limit_min> from source_asset: asset_code: <source_asset_code> asset_type: <source_asset_type> issuer_id: <participant_id> to target_asset: asset_code <target_asset_code> asset_type: <target_asset_type> issuer_id: <target_issuer_id>, quote_service_url: <ofi_quote_service_url>
    And id: <participant_id> get quote from requestID check rfi: <rfi_participant_id> was in the quote list and status: <quotes_initial_stauts> , quote_service_url: <ofi_quote_service_url>
    And id: <rfi_participant_id> pick up message from RFI_QUOTES topic sent by ofi <participant_id> should get time_expire: <ofi_time_expire> limit_max: <limit_max> limit_min: <limit_min> from asset_code: <source_asset_code> asset_type: <source_asset_type> issuer_id: <participant_id> to asset_code <target_asset_code> asset_type: <target_asset_type> issuer_id: <target_issuer_id>, wwGatewayURL: <rfi_wwGatewayURL>
    When id: <rfi_participant_id> check quotes status: <quotes_initial_stauts> from quotes_id, quote_service_url: <rfi_quote_service_url>
    And id: <rfi_participant_id> response quotes, account_name_receive: <rfi_account_name_receive> account_name_send: <rfi_account_name_send> exchange_rate: <exchange_rate> limit_max: <rfi_exchange_limit_max> response_time_expire: <rfi_exchange_time_expire> response_time_start: <rfi_exchange_time_start> to quote request time_expire: <ofi_time_expire> limit_max: <limit_max> limit_min: <limit_min> from source_asset: asset_code: <source_asset_code> asset_type: <source_asset_type> issuer_id: <source_issuer_id> to target_asset: asset_code <target_asset_code> asset_type: <target_asset_type> issuer_id: <target_issuer_id> by ofi: <participant_id>, crypto_service_url: <rfi_crypto_service_url>
    And id: <rfi_participant_id> post response, quote_service_url: <rfi_quote_service_url>
    And id: <participant_id> get quote from requestID check rfi: <rfi_participant_id> was in the quote list and status: <quotes_rfi_posted_stauts> , quote_service_url: <ofi_quote_service_url>
    And id: <rfi_participant_id> check quotes status: <quotes_rfi_posted_stauts> from quotes_id, quote_service_url: <rfi_quote_service_url>
    And id: <participant_id> sign quotes request with exchange_amount: <ofi_exchange_amount> account_name_receive: <ofi_account_name_receive> account_name_send: <ofi_account_name_send>, crypto_service_url: <ofi_crypto_service_url>
    And id: <participant_id> post exchange, quote_service_url: <ofi_quote_service_url>
    Then id: <rfi_participant_id> check quotes status: <quotes_finished_stauts> from quotes_id, quote_service_url: <rfi_quote_service_url>
    And id: <rfi_participant_id> pick up payment message , wwGatewayURL: <rfi_wwGatewayURL>
    And id: <participant_id> pick up payment message , wwGatewayURL: <ofi_wwGatewayURL>


    Examples:
      | global_whitelist_url           | participant_api_url             | participant_id             | rfi_participant_id         | ofi_exchange_amount                     | quotes_initial_stauts      | quotes_rfi_posted_stauts          | quotes_finished_stauts          | rfi_account_name_receive                     | rfi_account_name_send                        | ofi_account_name_receive                     | ofi_account_name_send                        | exchange_rate                         | rfi_exchange_limit_max                     | rfi_exchange_time_expire                              | rfi_exchange_time_start                              | ofi_quote_service_url             | rfi_quote_service_url             | ofi_time_expire                                      | limit_max                                  | limit_min                                  | source_asset_code                   | source_asset_type                        | source_issuer_id           | target_asset_code                   | target_asset_type                        | target_issuer_id           | ofi_crypto_service_url             | rfi_crypto_service_url             | rfi_wwGatewayURL                      | ofi_wwGatewayURL                      |
      | "ENV_KEY_PARTICIPANT_1_WL_URL" | "ENV_KEY_PARTICIPANT_1_API_URL" | "ENV_KEY_PARTICIPANT_1_ID" | "ENV_KEY_PARTICIPANT_2_ID" | "ENV_KEY_PARTICIPANT_1_EXCHANGE_AMOUNT" | "ENV_KEY_QUOTE_INI_STATUS" | "ENV_KEY_QUOTE_RFI_POSTED_STATUS" | "ENV_KEY_QUOTE_FINISHED_STATUS" | "ENV_KEY_PARTICIPANT_1_ISSUING_ACCOUNT_NAME" | "ENV_KEY_PARTICIPANT_1_ISSUING_ACCOUNT_NAME" | "ENV_KEY_PARTICIPANT_1_ISSUING_ACCOUNT_NAME" | "ENV_KEY_PARTICIPANT_1_ISSUING_ACCOUNT_NAME" | "ENV_KEY_PARTICIPANT_1_EXCHANGE_RATE" | "ENV_KEY_PARTICIPANT_1_EXCHANGE_LIMIT_MAX" | "ENV_KEY_PARTICIPANT_1_EXCHANGE_RESPONSE_EXPIRE_TIME" | "ENV_KEY_PARTICIPANT_1_EXCHANGE_RESPONSE_START_TIME" | "ENV_KEY_PARTICIPANT_1_QUOTE_URL" | "ENV_KEY_PARTICIPANT_2_QUOTE_URL" | "ENV_KEY_PARTICIPANT_1_EXCHANGE_REQUEST_EXPIRE_TIME" | "ENV_KEY_PARTICIPANT_1_EXCHANGE_LIMIT_MAX" | "ENV_KEY_PARTICIPANT_1_EXCHANGE_LIMIT_MIN" | "ENV_KEY_PARTICIPANT_1_ISSUE_ASSET" | "ENV_KEY_PARTICIPANT_1_ISSUE_ASSET_TYPE" | "ENV_KEY_PARTICIPANT_1_ID" | "ENV_KEY_PARTICIPANT_2_ISSUE_ASSET" | "ENV_KEY_PARTICIPANT_2_ISSUE_ASSET_TYPE" | "ENV_KEY_PARTICIPANT_2_ID" | "ENV_KEY_PARTICIPANT_1_CRYPTO_URL" | "ENV_KEY_PARTICIPANT_2_CRYPTO_URL" | "ENV_KEY_PARTICIPANT_2_WWGATEWAY_URL" | "ENV_KEY_PARTICIPANT_1_WWGATEWAY_URL" |
# | "ENV_KEY_PARTICIPANT_2_WL_URL" | "ENV_KEY_PARTICIPANT_2_API_URL" | "ENV_KEY_PARTICIPANT_2_ID" | "ENV_KEY_PARTICIPANT_1_ID" | "ENV_KEY_PARTICIPANT_2_EXCHANGE_AMOUNT" | "ENV_KEY_QUOTE_INI_STATUS" | "ENV_KEY_QUOTE_RFI_POSTED_STATUS" | "ENV_KEY_QUOTE_FINISHED_STATUS" | "ENV_KEY_PARTICIPANT_2_ISSUING_ACCOUNT_NAME" | "ENV_KEY_PARTICIPANT_2_ISSUING_ACCOUNT_NAME" | "ENV_KEY_PARTICIPANT_2_ISSUING_ACCOUNT_NAME" | "ENV_KEY_PARTICIPANT_2_ISSUING_ACCOUNT_NAME" | "ENV_KEY_PARTICIPANT_2_EXCHANGE_RATE" | "ENV_KEY_PARTICIPANT_2_EXCHANGE_LIMIT_MAX" | "ENV_KEY_PARTICIPANT_2_EXCHANGE_RESPONSE_EXPIRE_TIME" | "ENV_KEY_PARTICIPANT_2_EXCHANGE_RESPONSE_START_TIME" | "ENV_KEY_PARTICIPANT_2_QUOTE_URL" | "ENV_KEY_PARTICIPANT_1_QUOTE_URL" | "ENV_KEY_PARTICIPANT_2_EXCHANGE_REQUEST_EXPIRE_TIME" | "ENV_KEY_PARTICIPANT_2_EXCHANGE_LIMIT_MAX" | "ENV_KEY_PARTICIPANT_2_EXCHANGE_LIMIT_MIN" | "ENV_KEY_PARTICIPANT_2_ISSUE_ASSET" | "ENV_KEY_PARTICIPANT_2_ISSUE_ASSET_TYPE" | "ENV_KEY_PARTICIPANT_2_ID" | "ENV_KEY_PARTICIPANT_1_ISSUE_ASSET" | "ENV_KEY_PARTICIPANT_1_ISSUE_ASSET_TYPE" | "ENV_KEY_PARTICIPANT_1_ID" | "ENV_KEY_PARTICIPANT_2_CRYPTO_URL" | "ENV_KEY_PARTICIPANT_1_CRYPTO_URL" | "ENV_KEY_PARTICIPANT_1_WWGATEWAY_URL" | "ENV_KEY_PARTICIPANT_2_WWGATEWAY_URL"|
