
[DISTRIBUTION_ACCOUNTS]

  [DISTRIBUTION_ACCOUNTS.default]
    NODE_ADDRESS = "GAM5QC6M26ZWMOZZL6SANRZ6RGYAWRQJDEWBALHYZWWGIUCVAGAJD4ZF"
    NODE_SEED = "(seed value)"

  [DISTRIBUTION_ACCOUNTS.sagu]
    NODE_ADDRESS = "GCPB2TJK4CHAXESIGZIHVJMBQ2SK4I6UUKHPU7BWL7MCJF3ESC7SZ6TG"
    NODE_SEED = "(seed value)"

  [DISTRIBUTION_ACCOUNTS.seema]
    NODE_ADDRESS = "GBJT2KDHBTNRNZVCFPWLDIMUSJTRU5SZIDXJCGIKLGX5F2DYTXJE2BS2"
    NODE_SEED = "(seed value)"

  [DISTRIBUTION_ACCOUNTS.sudu]
    NODE_ADDRESS = "GCT4BZS42IKHOE5UGDL4IJ7LE2UYCG4SQHLR7TGUEK6VPFHYYVXVV6EK"
    NODE_SEED = "(seed value)"

[ISSUING_ACCOUNT]
  NODE_ADDRESS = "GA3UQQ7HQC4JJZCQO5IWZDZRJV2UHY5SS6MOU36H2QSIBNATZAXJZSMK"
  NODE_SEED = "(seed value)"

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GCZN5K3MKKTYHZ6RLOJHOH3W7WUIKSYCOZXFJYF6DWGWEPEGAS4MTPIV"
  NODE_SEED = "(seed value)"
[WHITE_LIST]
  [WHITE_LIST.uk]
  PARTICIPANT_DOMAIN = "uk.one.payments.gftn.io"
  [WHITE_LIST.au]
  PARTICIPANT_DOMAIN = "au.one.payments.gftn.io"
