// © Copyright IBM Corporation 2020. All rights reserved.
// SPDX-License-Identifier: Apache2.0
// 
package constant

var (
	PAYMENT_STATUS_INITIAL                       = "INITIALIZED"
	PAYMENT_STATUS_VALIDATION_FAIL               = "VALIDATION_FAIL"
	PAYMENT_STATUS_VALIDATION_SUCCESS            = "VALIDATION_SUCCESS"
	PAYMENT_STATUS_FEDERATION_COMPLIANCE_SUCCESS = "FEDERATION_COMPLIANCE_SUCCESS"
	PAYMENT_STATUS_FEDERATION_COMPLIANCE_FAIL    = "FEDERATION_COMPLIANCE_FAIL"
	PAYMENT_STATUS_CANCELLATION_ACCEPTED         = "PAYMENT_CANCELLATION_ACCEPTED"
	PAYMENT_STATUS_CANCELLATION_REJECTED         = "PAYMENT_CANCELLATION_REJECTED"
	PAYMENT_STATUS_RDO_INIT                      = "RDO_INITIALIZED"
	PAYMENT_STATUS_ASSET_REDEMPTION_INIT         = "ASSET_REDEMPTION_INITIALIZED"
	PAYMENT_STATUS_CANCELLATION_INIT             = "CANCELLATION_INITIALIZED"
	PAYMENT_STATUS_UNABLE_TO_APPLY               = "UNABLE_TO_EXECUTE"
	PAYMENT_STATUS_MODIFY_PAYMENT                = "REQUEST_TO_MODIFY_PAYMENT"
	PAYMENT_STATUS_RFI_VALIDATION_SUCCESS        = "RFI_VALIDATION_SUCCESS"
	PAYMENT_STATUS_RFI_VALIDATION_FAIL           = "RFI_VALIDATION_FAIL"
	PAYMENT_STATUS_OFI_VALIDATION_SUCCESS        = "OFI_VALIDATION_SUCCESS"
	PAYMENT_STATUS_OFI_VALIDATION_FAIL           = "OFI_VALIDATION_FAIL"
	PAYMENT_STATUS_RDO_FAIL                      = "RDO_FAIL"
	PAYMENT_STATUS_RDO_SUCCESS                   = "RDO_SUCCESS"
	PAYMENT_STATUS_SUBMIT_FAIL                   = "SUBMIT_FAIL"
	PAYMENT_STATUS_UPDATE_FIREBASE_FAIL          = "UPDATE_FIREBASE_FAIL"
	PAYMENT_STATUS_CLEARED                       = "CLEARED"
	PAYMENT_STATUS_SETTLED                       = "SETTLED"
	PAYMENT_STATUS_RETURNED                      = "PAYMENT_RETURNED"
	PAYMENT_STATUS_REJECTED                      = "CANCELLATION_REJECTED"
	PAYMENT_STATUS_ACTC                          = "ACTC"
	PAYMENT_STATUS_RCVD                          = "RCVD"
	PAYMENT_STATUS_RJCT                          = "RJCT"
	PAYMENT_STATUS_CANC                          = "CANC"
	PAYMENT_STATUS_FTHI                          = "FTHI"
	PAYMENT_STATUS_RJCR                          = "RJCR"
	PAYMENT_TYPE_CANCELLATION                    = "cancellation"
	PAYMENT_TYPE_CREDIT_TRANSFER                 = "credit_transfer"
	PAYMENT_TYPE_ASSET_REDEMPTION                = "asset_redemption"
	PAYMENT_TYPE_RDO                             = "digital_obligation_notification"
	PAYMENT_TYPE_EXCEPTION                       = "exception"
	PAYMENT_STATUS_RFI_PROCESSING                = "RFI_PROCESSING"
	PAYMENT_STATUS_OFI_PROCESSING                = "OFI_PROCESSING"
	PAYMENT_STATUS_FAILED                        = "FAILED"
	PAYMENT_STATUS_FED_COMP_SUCCESS              = "FEDERATION_COMPLIANCE_ACCEPTED"
	PAYMENT_STATUS_FED_COMP_REJECT               = "FEDERATION_COMPLIANCE_REJECTED"
	PAYMENT_STATUS_ASSET_REDEMPTION_REJECT       = "ASSET_REDEMPTION_REJECTED"
	PAYMENT_STATUS_ASSET_REDEMPTION_ACCEPT       = "ASSET_REDEMPTION_ACCEPTED"
)

var (
	PACS002_SUPPLEMENTARY_DATA_ISSUER          = "/Message/FIToFIPmtStsRpt/TxInfAndSts/Issr"
	PACS002_SUPPLEMENTARY_DATA_ACCOUNT_ADDRESS = "/Message/FIToFIPmtStsRpt/TxInfAndSts/SttlmAcctAddr"
	PACS002_SUPPLEMENTARY_DATA_PAY_REFERENCE   = "/Message/FIToFIPmtStsRpt/TxInfAndSts/PayToRef"
)

var (
	PACS009_SUPPLEMENTARY_DATA_BANK_NAME      = "/Message/CdtTrfTxInf/DepositDetails/BankName"
	PACS009_SUPPLEMENTARY_DATA_BRANCH         = "/Message/CdtTrfTxInf/DepositDetails/Branch"
	PACS009_SUPPLEMENTARY_DATA_PAYMENT_METHOD = "/Message/CdtTrfTxInf/DepositDetails/PaymentMethod"
	PACS009_SUPPLEMENTARY_DATA_ACCOUNT_NUMBER = "/Message/CdtTrfTxInf/DepositDetails/AccountNumber"
	PACS009_SUPPLEMENTARY_DATA_ACCOUNT_TYPE   = "/Message/CdtTrfTxInf/DepositDetails/AccountType"
)
