version: '2.0'
services:

  admin.ww.io:
    image: gftn/global-whitelist-service
    container_name: global-whitelist-service
    ports:
      - "11234:11234"
    volumes:
      - /var/log/gftn:/opt/global-whitelist-service/logs
      - ./:/var/secret
    env_file:
     - ./.env