
[ANCHOR_ACCOUNTS]

  [ANCHOR_ACCOUNTS.nzd-anchor-com]
    NODE_ADDRESS = "GDVEAQUY2MA6XWHPQHPXE44PYYAB65WGPAIXY3BYUMMYPQNBNFR2G4UW"
    NODE_PASS_CODE = "656496134290761ea16eb1bce81fd3e38399f094756f42eeee1eeb106aa6c94c"
    NODE_SEED = ""

  [ANCHOR_ACCOUNTS.usd-anchor-com]
    NODE_ADDRESS = "GDVEAQUY2MA6XWHPQHPXE44PYYAB65WGPAIXY3BYUMMYPQNBNFR2G4UW"
    NODE_PASS_CODE = "077a672e0a65977a63f3ca650257807f17a9654438e797e2064be2795d9d4b7e"
    NODE_SEED = ""

[IBM_TOKEN_ACCOUNT]
  NODE_ADDRESS = "GD2RP3XK2AU2NMMG5AIXBBIZVPGKBUZVKIUTT5NCXG6LHD6FFN7UJGW2"
  NODE_PASS_CODE = ""
  NODE_SEED = "(seed value)"
