apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose-3zk-3b-ssl.yaml
    kompose.version: 1.17.0 ()
  creationTimestamp: null
  labels:
    app: zookeeper-3
  name: zookeeper-3
spec:
  ports:
  - name: client
    port: 32181
    targetPort: 32181
  - name: election
    port: 3888
    targetPort: 3888
  - name: server
    port: 2888
    targetPort: 2888
  selector:
    app: zookeeper-3
#status:
#  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: zookeeper-3-headless
  name: zookeeper-3-headless
spec:
  clusterIP: None
  ports:
  - name: client
    port: 32181
    protocol: TCP
    targetPort: 2181
  - name: election
    port: 3888
    protocol: TCP
    targetPort: 3888
  - name: server
    port: 2888
    protocol: TCP
    targetPort: 2888
  selector:
    app: zookeeper-3
  sessionAffinity: None
  type: ClusterIP